export const GET_PEARSON_USER = 'GET_PEARSON_USER';
export const GET_PEARSON_USER_SUCCESS = 'GET_PEARSON_USER_SUCCESS';
export const GET_PEARSON_USER_FAILURE = 'GET_PEARSON_USER_FAILURE';
export const DELETE_PEARSON_USER = 'DELETE_PEARSON_USER';
